version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: landguard-postgis
    command: postgres -c 'password_encryption=md5'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: landguard
    ports:
      - "5433:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
